runtime: custom
runtime_config:
  python_version: 3
env: flex
# entrypoint: gunicorn -b:$PORT index:app
resources:
  disk_size_gb: 20 
liveness_check:
  path: "/liveness_check"
  check_interval_sec: 30
  timeout_sec: 4
  failure_threshold: 2
  success_threshold: 2
readiness_check:
  path: "/readiness_check"
  check_interval_sec: 5
  timeout_sec: 4
  failure_threshold: 2
  success_threshold: 2
  app_start_timeout_sec: 300